version: "3"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "3003:3003"
    command: "node server.js"
